# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dde21fc21aa399f30b99fb66513879744903b7248537cd7ac199c5ccae293eae7654200ec660b7ae65ca15a98a91c76a29d80cfd7d0c90a7a39ef8d3c6c7112f

test:
  secret_key_base: e55b174a660eef463621ed768311ef15926312b135aa6d3639bfc783d3a41eb013244a5fbb959445d933cd72208c22c413e71d54ccaa74f4e79c7ada1a3e6f5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
